services:
  postgres:
    image: postgres:16
    container_name: hospital-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hospital_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init_schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql

volumes:
  postgres_data: